import './globals.css'
import { Inter } from 'next/font/google'
import Provider from './Context/AuthContext'
import ToasterContext from './context/toastercontext'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'MedTrak',
  description: 'Generated by YassEngineer',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}><Provider><ToasterContext />{children}</Provider></body>
    </html>
  )
}
